fix build

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -23,102 +23,105 @@ jobs:
     steps:
       - name: Git checkout
         uses: actions/checkout@v3
-            
-      - uses: actions/setup-node@v3
+
+      - name: Build app   
+        uses: actions/setup-node@v3
         with:
           node-version: 16
-      - run: cd app
-      - run: npm install
-      - run: npm run build
-
-      - name: Configure AWS credentials from AWS account
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-to-assume: ${{ secrets.AWS_ROLE }}
-          aws-region: ${{ secrets.AWS_REGION }}
-          role-session-name: GitHub-OIDC-TERRAFORM
-
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.3.3
-
-      - name: Terraform fmt
-        id: fmt
-        run: terraform fmt -check ./terraform
-        continue-on-error: false
-
-      - name: Terraform Init
-        id: init
-        env:
-          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
-          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
         run: |
-          cd ./terraform
-          terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"
+          cd app
+          npm install
+          npm run build
 
-      - name: Terraform Plan
-        id: plan
-        run: |
-          cd ./terraform
-          terraform plan -no-color
-        continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+  #     - name: Configure AWS credentials from AWS account
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         role-to-assume: ${{ secrets.AWS_ROLE }}
+  #         aws-region: ${{ secrets.AWS_REGION }}
+  #         role-session-name: GitHub-OIDC-TERRAFORM
 
-  apply:
-    runs-on: ubuntu-latest
-    needs: plan
-    environment:
-        name: staging
-    defaults:
-      run:
-        shell: bash
-        working-directory: .
-    steps:
-      - name: Git checkout
-        uses: actions/checkout@v3
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: 1.3.3
 
-      - name: Configure AWS credentials from AWS account
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-to-assume: ${{ secrets.AWS_ROLE }}
-          aws-region: ${{ secrets.AWS_REGION }}
-          role-session-name: GitHub-OIDC-TERRAFORM
+  #     - name: Terraform fmt
+  #       id: fmt
+  #       run: terraform fmt -check ./terraform
+  #       continue-on-error: false
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.3.3
+  #     - name: Terraform Init
+  #       id: init
+  #       env:
+  #         AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
+  #         AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
+  #       run: |
+  #         cd ./terraform
+  #         terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"
 
-      - name: Terraform fmt
-        id: fmt
-        run: terraform fmt -check ./terraform
-        continue-on-error: false
+  #     - name: Terraform Plan
+  #       id: plan
+  #       run: |
+  #         cd ./terraform
+  #         terraform plan -no-color
+  #       continue-on-error: true
 
-      - name: Terraform Init
-        id: init
-        env:
-          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
-          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
-        run: |
-          cd ./terraform
-          terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"
+  #     - name: Terraform Plan Status
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1
 
-      - name: Terraform Plan
-        id: plan
-        run: |
-          cd ./terraform
-          terraform plan -no-color
-        continue-on-error: true
+  # apply:
+  #   runs-on: ubuntu-latest
+  #   needs: plan
+  #   environment:
+  #       name: staging
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #       working-directory: .
+  #   steps:
+  #     - name: Git checkout
+  #       uses: actions/checkout@v3
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+  #     - name: Configure AWS credentials from AWS account
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         role-to-assume: ${{ secrets.AWS_ROLE }}
+  #         aws-region: ${{ secrets.AWS_REGION }}
+  #         role-session-name: GitHub-OIDC-TERRAFORM
+
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: 1.3.3
+
+  #     - name: Terraform fmt
+  #       id: fmt
+  #       run: terraform fmt -check ./terraform
+  #       continue-on-error: false
+
+  #     - name: Terraform Init
+  #       id: init
+  #       env:
+  #         AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
+  #         AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
+  #       run: |
+  #         cd ./terraform
+  #         terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"
+
+  #     - name: Terraform Plan
+  #       id: plan
+  #       run: |
+  #         cd ./terraform
+  #         terraform plan -no-color
+  #       continue-on-error: true
+
+  #     - name: Terraform Plan Status
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1
         
-      - name: Terraform Apply
-        run: |
-          cd ./terraform
-          terraform apply --auto-approve
+  #     - name: Terraform Apply
+  #       run: |
+  #         cd ./terraform
+  #         terraform apply --auto-approve
